### ISSUE TITLE
Support Temporary Basal Rates with percentage values

### ISSUE THREAD

**Issue by samspycher** [AAPS-Omnipod/AndroidAPS#10]
Setting a TBR with a percentage value results in this log message:

```
09:16:57.440 [Thread-4823] D/PUMP: [OmnipodPumpPlugin.setTempBasalPercent():902]: setTempBasalPercent [OmnipodPumpPlugin] - Not implemented.
```

This can be reproduced with two phones, where the non-AAPS phone sends the following command to the AAPS phone via SMS message:

1. Install & configure AAPS, and set up remote SMS commands as described [here](https://androidaps.readthedocs.io/en/latest/EN/Children/SMS-Commands.html#sms-commands)
1. Send e.g.  the SMS `BASAL 105% 10` from non-AAPS to AAPS phone
1. After receiving response from AAPS phone, enter Authenticator Key and Secret
1. Wait for response message indicating failure
1. Verify missing feature in log at time of SMS exchange.

Example exchange:
<img width="400" alt="WhatsApp Image 2020-10-02 at 09 17 26" src="https://user-images.githubusercontent.com/1706327/94908395-e1d4d680-04a1-11eb-8aa4-caf588074066.jpeg">

**Comment by bartsopers** [comment]
Fixed by @samspycher
