### ISSUE TITLE
Fix SMS response values for basal rate and duration when setting TBR via SMS

### ISSUE THREAD

**Issue by samspycher** [AAPS-Omnipod/AndroidAPS#12]
Treating TBR via SMS works well, however the response SMS sent by AAPS contains values of -1 for both the new temp basal rate and the duration in minutes (see image below). 

Recording this issue at the current knowledge state for now, and will update with matching log messages and/or further insight later.

<img width="400" alt="Screenshot 2020-10-02 at 21 52 36" src="https://user-images.githubusercontent.com/1706327/94965509-ee861880-04fb-11eb-8f56-bd8ac2380f26.png">

**Comment by samspycher** [comment]
A further look at the code reveals that these values are missing from the `OmnipodPumpPlugin` response.

`AapsOmnipodManager` seems to return a relatively minimalist `PumpEnactResult` => L484: 
```
return new PumpEnactResult(injector).success(true).enacted(true); 
```
This return object e.g. does not contain the enacted duration and rate. 

Looking further down the chain, called methods are missing return values (`AapsOmnipodManager.setTemporaryBasal`), to set the response with. However the Action itself (`SetTempBasalAction`) does seem to return a `StatusResponse`, which may contain the relevant items (rate and duration set by the pod). 

If `StatusResponse` turns out to contain the required values, the return values in methods can be adapted to enrich the SMS response with appropriate data.

**Comment by bartsopers** [comment]
Fixed by @samspycher
