### ISSUE TITLE
Suggestion: The activation of a new pod in "Pod management" should lead directly to the OVERVIEW or OMNIPOD tab

### ISSUE THREAD

**Issue by dar-kod** [AAPS-Omnipod/AndroidAPS#16]
AndroidAPS 2.7.0-omnipod-0.4-SNAPSHOT
Build: 6fa01f88e-2020.10.06-19.51

After a pod activation in POD MGMT or **Pod management** -> **Activate Pod** by clicking the next button returns you to **Pod management** screen, where the button **Deactivate Pod** might be pressed unintentionally and cause to lose a pod. I would suggest going directly back to **OVERVIEW** or **OMNIPOD** tab. That would increase the security for some users.

**Comment by bartsopers** [comment]
Won't do anymore because there are now also more actions (like play a test beep) on the Pod management menu.
