### ISSUE TITLE
AAPS receives delayed Dex patched app bg data  

### ISSUE THREAD

**Issue by paddingtonil** [AAPS-Omnipod/AndroidAPS#17]
AAPS 2.7 Omnipod 0.4 build 45F620cb1 
Bg data from dex patched app delayed in 10 min approximately.  
[AndroidAPS_LOG_1602267554492.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5356842/AndroidAPS_LOG_1602267554492.log.zip)

**Comment by bartsopers** [comment]
This is a core issue: https://github.com/nightscout/AndroidAPS/issues/28
