### ISSUE TITLE
Suspend button on Omnipod tab shows wrong icon on Overview tab

### ISSUE THREAD

**Issue by eurenda** [AAPS-Omnipod/AndroidAPS#22]
![20201017_111024](https://user-images.githubusercontent.com/1902827/96350196-770ec800-1069-11eb-9391-3a705f24fcc2.jpg)
On 0.4 builds (currently on g2d4f13) the _Suspend_ button on the _Omnipod_ tab/module which for Omnipod pumps suspends the pump and stops **all insulin delivery** currently shows a _Suspend_  icon on the _Overview_ tab/module.

The icon that should be shown on the _Overview_ tab/module is a _Suspend_ icon without time indication as this was user initiated and particular to Omnipod pumps and it should be a **Disconnected** button with no time indication as this was user initiated.

To replicate:

- From _Omnipod_ tab hit _Suspend_ button

- upon confirmation of Suspend go to _Overview_ tab

- See that loop status shows _Suspend_ which does not fit AAPS definition as in Omnipod case this pod suspension suspends **ALL** insulin delivery and should show **_Disconnected_**

The above is being reported as part of the [loop status](https://androidaps.readthedocs.io/en/latest/EN/Getting-Started/Screenshots.html#loop-status)  loop status definitions

**Comment by bartsopers** [comment]
@eurenda and I discussed this on Discord. This has been addressed in c16fc3a946dfbe9ce3e1a33225830df36a38e734. We also chose to hide the disconnect buttons in the overview for Omnipod.
