### ISSUE TITLE
Pod fault: 49 INSULINE_DELIVERY_COMMAND_ERROR

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS#23]
**AndroidAPS 2.7.0-omnipod-0.4-SNAPSHOT**
Build: EROS_0.2-1871-gf3ec65289
Flavor: fullrelease

**Phone:**
Samsung Note9 (SM-N960F, Android 10)

**Problem description:**
Unexpected Pod fault: 49 INSULINE_DELIVERY_COMMAND_ERROR
Just a few minutes after executing a bolus.
Pod active for about 17 hours.

_Additional "context" info:_
Not doing anything special with AAPS. The phone did however had been less responsive for short periods due to a problem with my Outlook mail client app. It does not use or depend on BT but I can imagine it changed timing on handling Pod responses?
I just had been testing and force-closing the Outlook app some time before when the 49 error occurred.

**Comment by vanelsberg** [comment]
![Screenshot_20201019-094905_AndroidAPS](https://user-images.githubusercontent.com/45144129/96512482-d71b8f00-1260-11eb-834a-e249f870d1e1.jpg)
[AndroidAPS_LOG_1603094668241.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5404788/AndroidAPS_LOG_1603094668241.log.zip)

**Comment by bartsopers** [comment]
Fixed in omnipod_eros_dev
