### ISSUE TITLE
Screaming pod with no error message toward end of pod life

### ISSUE THREAD

**Issue by afreitag33** [AAPS-Omnipod/AndroidAPS#24]
Two pods turned into screamers with no error message in AAPS toward the end of their natural life (68 and 70 hours). These are the only two pods that I've had so far with SMB on, so might have something to do with that draining a battery or otherwise causing a problem, and it never happened without using SMB. Both screamers couldn't be regularly deactivated and had to be silenced via paper clip in the back, and wouldn't refresh using the button in AAPS (warning appeared when I tried: "failed to refresh status: communication failed: failed to decode message from the Pod").

AAPS Build EROS-0.2-1852-g6fa01f88e-2020.10.02-09:07

Logs as follows, first fail at 16:11
[AndroidAPS_LOG_1602879922596.log (1).zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5405600/AndroidAPS_LOG_1602879922596.log.1.zip)

Fail at 2:52
[AndroidAPS_LOG_1603141377416.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5405601/AndroidAPS_LOG_1603141377416.log.zip)

**Comment by ZandMarc** [comment]
Maybe related or the same as the issue I posted (https://github.com/AAPS-Omnipod/AndroidAPS/issues/33). My pods started screaming when nearly at the end of their life, while issuing a SMB, so...

**Comment by bartsopers** [comment]
This Pod fault  is probably related to battery depletion. in #37, we aim to address this by reducing the amount of communication with the Pod.
