### ISSUE TITLE
AAPS crashes continuously: DST problem?

### ISSUE THREAD

**Issue by ZandMarc** [AAPS-Omnipod/AndroidAPS#29]
Tonight around 23:30 I found that AAPS had stopped. I tried several times to stop and start it again, tried with restarting my phone, turning off BT when starting, removed AAPS and installed it again, but to no avail: AAPS kept crashing. Until I turned off my RileyLink and started again. That worked, but meanwhile it was also 00.05. And when I restarted my RL and it tried to connect to my running pod, it wouldn't connect. OP status tab showed last connection with pod 1 day and 22 hrs ago, expiration of pod 2 days ago (screenshot attached). Considering the latter, I think this issue is related to daylight savings time which started today. (problem with pod solved by starting a new one)
Build: EROS_0.2-1860-g2d4f1378b-2020.10.16-14:38
[AndroidAPS.log](https://github.com/AAPS-Omnipod/AndroidAPS/files/5436124/AndroidAPS.log)
![Screenshot_20201026-000938 1](https://user-images.githubusercontent.com/31537397/97121914-0e3ae600-1722-11eb-8887-cce596136418.png)

**Comment by ZandMarc** [comment]
Hmm, come to think of it, this build can't be installed with a running pod. So the strange data about the running pod is probably not related to DST, but is caused by me deleting and re-installing AAPS.

**Comment by DorianScholz** [comment]
Had the same issue of AAPS crashing few seconds after every start, starting from 23:00 on the Sunday of the DST start.
Was able to recover by deleting AAPS app data and then importing settings again.
But lost the active pod due to this.
Activation of new pod was initially hampered by #30.

**Comment by DorianScholz** [comment]
Log file showing multiple AAPS restarts from 23:13 to 23:17 but without obvious reasons for the crashes:
[AndroidAPS._2020-10-25_23-17-20.log](https://github.com/AAPS-Omnipod/AndroidAPS/files/5447107/AndroidAPS._2020-10-25_23-17-20.log)

**Comment by vanelsberg** [comment]
Thanks for reporting this.
A fix is currently under testing and will be included in the final release.

**Comment by bartsopers** [comment]
Yes, definitely DST related. Fixed.
