### ISSUE TITLE
Initializing new pod failed with "Invalid duration" due to DST

### ISSUE THREAD

**Issue by DorianScholz** [AAPS-Omnipod/AndroidAPS#30]
Version: AAPS 2.7 Omnipod 0.4

After hitting #29 I had to start a new pod.
But this initially failed with the error: Invalid duration
The pod was primed OK, but this error occurred just before the needle would be injected.
This was at about 23:45 of the day DST started.

After switching off "DST/Time zone detection" I was able to continue with the needle injection.
But by the time I tried this, it was already past midnight, so that might also have been what made it work again.

**Comment by DorianScholz** [comment]
Log file of two unsuccessful attempts to continue with needle injection at 23:53:10 and 23:53:20:
[AndroidAPS_DST_pump_init_Invalid_duration.log](https://github.com/AAPS-Omnipod/AndroidAPS/files/5447086/AndroidAPS_DST_pump_init_Invalid_duration.log)

**Comment by DorianScholz** [comment]
Another log file from a few minutes later.
Another failed attempt of insertCannula at 00:00:14 (14 secs after midnight), so this suggests it was not the change of date that made it finally work.
Then I switched off the "DST/Time zone detection" some time between 00:00:14 and 00:02:45. 
And the next attempt of insertCannula at 00:02:45 worked...
[AndroidAPS._2020-10-26_00-03-29.log](https://github.com/AAPS-Omnipod/AndroidAPS/files/5447872/AndroidAPS._2020-10-26_00-03-29.log)

**Comment by vanelsberg** [comment]
Thanks for reporting this.
A fix is currently under testing and will be included in the final release.

**Comment by bartsopers** [comment]
Fixed
