### ISSUE TITLE
Frequent screamers towards end of pod life

### ISSUE THREAD

**Issue by ZandMarc** [AAPS-Omnipod/AndroidAPS#33]
Lately, I frequently get screaming pods a couple of hours before 72 hrs of use. It happens when the pod is issueing a bolus (SMB). From the one I had today, the error message in the log is "RESET_FROM_UNKNOWN_CAUSE" (or, that's what I think it is: I'm not that experienced in reading the logs). Log is attached. I don't think the error message is always the same. Earlier, the message was "ENCODER_COUNT_EXCESSIVE_VARIANCE" (second log attached). 

Build: Eros_0.2-1957-ga0da0fa0e-2020.10.30-10:41

[AndroidAPS_sreamer_endofpodlife.txt](https://github.com/AAPS-Omnipod/AndroidAPS/files/5480379/AndroidAPS_sreamer_endofpodlife.txt)
[screamer-tijdens-bolus-log.txt](https://github.com/AAPS-Omnipod/AndroidAPS/files/5480381/screamer-tijdens-bolus-log.txt)

**Comment by larsqvd** [comment]
@ZandMarc previous versions are not supported anymore you may want to upgrade to 0.4 first (as this solved a lot of issues). See the wiki with more information on upgrading.

**Comment by ZandMarc** [comment]
This is the dev-version from october 30th. That's the 0.4 version, as far as I know: version in "about" says "AndroidAPS 2.7-omnipod-0.4.1-SNAPSHOT". The 0.2 in the build number is not correct, I think.

**Comment by vanelsberg** [comment]
You are on the wrong/outdated branch.
This version is not supported.

Please update to 0.4 release version (**omnipod_eros** branche)?
https://github.com/AAPS-Omnipod/AndroidAPS/wiki

You might want to you our Discord channel for the latest updates...

**Comment by bartsopers** [comment]
This Pod fault  is probably related to battery depletion. in #37, we aim to address this by reducing the amount of communication with the Pod.
