### ISSUE TITLE
A Pod fault (049 INSULIN_DELIVERY_COMMAND_ERROR) has been detected.

### ISSUE THREAD

**Issue by dar-kod** [AAPS-Omnipod/AndroidAPS#34]
AndroidAPS 2.7.0-omnipod-0.4.0
Build version: c6c658237
Date and time of the error: 7 November 2020, 01:12 am

I wanted to change the pod after almost 80 hours, something like 1 minute before the end. I clicked to **REFRESH** status and there was some problem like couldn't connect to pod but still I went to **POD MGMT** and **Deactivate Pod**.

I prepared a new pod and clicked at **Activate Pod**. But then I heard clicking as usually but also the new pod was screaming at the same time. I first saw that it shows that there was a problem to connect with the pod and button to try again. That was not useful as the pod was screaming. A screenshot of this is attached. It is made at 01:12 am. The following text was on the screen:

**A Pod fault (049 INSULIN_DELIVERY_COMMAND_ERROR) has been detected. Please deactivate your Pod and activate a new one.**

It was the first time that I experience this error. The new pod was not out of date. I was advised to post this for investigation. Two screenshots and 1 log file are attached.

![Screenshot_20201107-011212_AndroidAPS](https://user-images.githubusercontent.com/24446806/98452128-d0d84e80-214c-11eb-8e2b-2d1b551ad4d2.jpg)
![Screenshot_20201107-011327_AndroidAPS](https://user-images.githubusercontent.com/24446806/98452132-d59d0280-214c-11eb-94fd-11abf3774488.jpg)
[AndroidAPS._2020-11-07_00-00-00_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5505500/AndroidAPS._2020-11-07_00-00-00_.0.zip)

**Comment by bartsopers** [comment]
Fixed in omnipod_eros_dev
