### ISSUE TITLE
import the settings for OmniPod Version 04

### ISSUE THREAD

**Issue by Thomas-Wolff** [AAPS-Omnipod/AndroidAPS#36]
Hello everyone

I have been looping for quite some time and updated to AndroidAPS 2.7.0-omnipod-04 in October. Everything went without any problems.
Phone: Samsung Galaxy A40
Yesterday morning I had exported my AAPS settings again before I had to perform my usual POD change, all fine.
Last night I wanted to import the settings again for testing, the import ran as described in the documentation perfectly.
Only my active pod I set in the morning smashed it, the expiration date and the time of the active pod it has put the import back on that of the old pod I had changed in the morning, so this one had passed the 80 hours far over. The result was that I was dead the pod last night and had to be changed again.
Maybe someone in this group can give me some information about what went wrong here or maybe I read something over the documentaries.
Otherwise I am very satisfied with the new 04 version, except for this little thing from last night.

With a kind greeting Thomas
[AndroidAPS._2020-11-08_19-37-51_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5522667/AndroidAPS._2020-11-08_19-37-51_.0.zip)
[AndroidAPS._2020-11-08_19-37-51_.1.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5522668/AndroidAPS._2020-11-08_19-37-51_.1.zip)
[AndroidAPS._2020-11-08_19-37-51_.2.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5522669/AndroidAPS._2020-11-08_19-37-51_.2.zip)
[AndroidAPS._2020-11-08_19-37-51_.3.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5522671/AndroidAPS._2020-11-08_19-37-51_.3.zip)
[AndroidAPS._2020-11-08_19-37-51_.4.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5522673/AndroidAPS._2020-11-08_19-37-51_.4.zip)
![Screenshot_20201028-124336_AndroidAPS](https://user-images.githubusercontent.com/59526802/98785153-736a2900-23fc-11eb-8d2c-54d3bfad8132.jpg)

**Comment by vanelsberg** [comment]
This is "know behavior": AAPS settings contain POD status info.
When importing settings, the current Pod information is overwritten by the Pod status in settings. If this is not your current active Pod you will loose it. (Btw: There are undocumented and unsupported ways to save the current Pod status and change an old settings file, provided it is unencrypted)

To discuss this please join our channel on Discord?
See https://github.com/AAPS-Omnipod/AndroidAPS/wiki

**Comment by Thomas-Wolff** [comment]
Schönen Dank für die Information, habe ich mir schon so in etwa gedacht.
Da ich aber erst seit kurzem Loope wusste ich es nicht so genau. Auf Discord werde ich keinen keine Diskussion dies bezüglich auslösen. So wie es ist, mit dem Wissen komme ich auch in Zukunft gut klar.
Schönen Dank noch einmal und einen schönen Abend.
Gruß Thomas

**Comment by vanelsberg** [comment]
FYI, Wiki contains some info on this:
https://github.com/AAPS-Omnipod/AndroidAPS/wiki/5-Troubleshooting#can-i-import-my-settings-file-when-on-an-active-pod
