### ISSUE TITLE
RL STATS screen - not showing correctly on Samsung Note 9

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS#38]
AndroidAPS 2.7.0-omnipod-0.4.0
Build: c6c658237-2020.10.27
Flavor: fullrelease

Phone:
Samsung Note9 (SM-N960F, Android 10)

Problem description:
Screen information (layout) for the RL STATS screen cropped (see screen print)

![xxx](https://user-images.githubusercontent.com/45144129/98864732-a64b0600-246a-11eb-8348-fcf9d4824b16.jpg)

**Comment by bartsopers** [comment]
Fixed

**Comment by vanelsberg** [comment]
Fix somehow did not make it into commit 56cf0d59?

![Screenshot_20201220-081423_AndroidAPS](https://user-images.githubusercontent.com/45144129/102707511-ef794b80-429b-11eb-99d5-242c3dc52400.jpg)

**Comment by vanelsberg** [comment]
Solved with omnipod_eros_dev, commit #a5a10146
