### ISSUE TITLE
Pod fault (049 INSULIN_DELIVERY_COMMAND_ERROR) when AAPS tries to set a new temp basal

### ISSUE THREAD

**Issue by fredrik-ljung** [AAPS-Omnipod/AndroidAPS#40]
AndroidAPS 2.7.0-omnipod-0.4.0
Build version: c6c6582
Date and time of the error: 8 November 2020, 12:39 and 15 November 2020, 08:39

The phone used is a Samsung Galaxy S20 SM-G980F

Two faults seen during one week. Nothing done with the phone at the time. It just suddenly starts to scream and reports pod fault "A Pod fault (049 INSULIN_DELIVERY_COMMAND_ERROR) has been detected. Please deactivate your Pod and activate a new one".

After looking a little bit in the loggs the two errors looks very similar. AAPS has set a long zero temp basal and is about to set a new one directly after the other one has expired. There is also a "Time, Date and/or TimeZone changed event" during the zero temp in both cases. Don't know if that is relevant. 

[Pod_fault_49_Logs.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5549806/Pod_fault_49_Logs.zip)

**Comment by bartsopers** [comment]
Fixed in omnipod_eros_dev
