### ISSUE TITLE
Question: Timeline

### ISSUE THREAD

**Issue by JanLoebel** [AAPS-Omnipod/AndroidAPS#55]
Hi there,

my sister is heavily using your branch of the omnipod. Beside the reconnection issue that sometimes happen with the rileylink she is very happy and did not have any bugs yet. Currently she's getting the warning that there is a new version available (since around 35 days) and some features are getting deactivated.

I wanted to ask if you guys have any timeline or idea when the development continuous and when you will be able or what is missing to migrate your new feature back into the AndroidAps project. And is there something you could need help with?

Best regards and many thanks for your awesome work so far!

**Comment by larsqvd** [comment]
Hi Jan,

Omnipod has been merged into AAPS main branch, your sister should start using the main branch instead of this one.

**Comment by JanLoebel** [comment]
@larsqvd thank you! I've totally missed that.. sorry!
